version: 2.1

jobs:
  build-docker-image:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/.devops
            source ~/.devops/bin/activate

      
      

  
workflows:
  default:
    jobs:
      - build-docker-image

