Description: >
    Ahmed Samir / FinalProject  
    Servers 

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
        
    AMItoUse:
        Description: AMI to use for our base image
        Type: String

Resources:


    WebInstance:
        Type: AWS::EC2::Instance
        Properties:
          KeyName: publicpublic
          UserData:
              Fn::Base64: !Sub |
                  #!/bin/bash
                  sudo su
                  apt-get update -y       
          InstanceType: t2.nano
          ImageId: !Ref AMItoUse
          InstanceType: t2.medium          
          KeyName: AWS_Ahmed
          BlockDeviceMappings:
          - DeviceName: "/dev/sdk"
            Ebs:
             VolumeSize: '10'     
          NetworkInterfaces: 
            - AssociatePublicIpAddress: "false"
              DeviceIndex: "0"
              GroupSet: 
                - Ref: BastionSecurityGroup
              SubnetId: 
                Fn::ImportValue:
                    !Sub "${EnvironmentName}-PUB-SN"


    BastionSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Bastion Host Security Group
            VpcId:
                Fn::ImportValue:
                    !Sub "${EnvironmentName}-VPCID"
            SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 22
              ToPort: 22
              CidrIp: 0.0.0.0/0
##########################################################
    WebInstance:
        Type: AWS::EC2::Instance
        Properties:
          KeyName: privateprivate
          UserData:
              Fn::Base64: !Sub |
                  #!/bin/bash
                  sudo su
                  apt-get update -y       
          InstanceType: t2.nano
          ImageId: !Ref AMItoUse
          InstanceType: t2.medium                 
          KeyName: AWS_Ahmed
          BlockDeviceMappings:
          - DeviceName: "/dev/sdk"
            Ebs:
             VolumeSize: '10'     
          NetworkInterfaces: 
            - AssociatePublicIpAddress: "false"
              DeviceIndex: "0"
              GroupSet: 
                - Ref: BastionSecurityGroup2
              SubnetId: 
                Fn::ImportValue:
                    !Sub "${EnvironmentName}-PRI2-SN"


    BastionSecurityGroup2:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Bastion Host Security Group
            VpcId:
                Fn::ImportValue:
                    !Sub "${EnvironmentName}-VPCID"
            SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 22
              ToPort: 22
              SourceSecurityGroupId: !Ref BastionSecurityGroup